### ISSUE TITLE
Create App Search implementation

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-search-service#10]
As a Silverstripe CMS developer, I want to be able to deploy an Elastic App Search
instance and index selected content types from my Silverstripe CMS project to that instance so that I can create an excellent search experience for end users of my project.

## Acceptance criteria

- [x] Zero-config opt-in (e.g. with environment variable change)
- ~~[ ] Declare fields for faceting in config~~
- ~~[ ] Set attributes for faceting in config~~
- [x] Declare searchable types in config
- [x] Declare implementation-specific options in config

## Excludes

- Querying the App Search instance

**Comment by unclecheese** [comment]
Removing the faceting ACs because AppSearch handles them query side https://swiftype.com/documentation/app-search/api/search/facets

**Comment by chillu** [comment]
Casting doesn't work yet, but that's in a different issue. Confirmed that add and remove of docs works.
