### ISSUE TITLE
environmentizeIndex is too rigid

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-search-service#14]
I think defaulting to including environment types in indexes is good, but in some cases there's multiple environments per type (e.g. `test1` vs. `test2`). Those are custom to your hosting solution (e.g. [platform variables](https://docs.silverstripe.cloud/cloud-features/variables/)). Can we allow interpolation of env constants in the index name, e.g. `myindex_%ENV_TYPE%` by default, and then you can customise to `myindex_%MY_ENV_NAME_VAR%`?

**Comment by michalkleiner** [comment]
Might be out of context here, but would that mean you have to reindex everything when switching environment type?

**Comment by chillu** [comment]
Yes, I think if your use case is to transition a site from e.g. "test" to "live" on the same index, then it's up to you to manage that transition. A dangerous option that avoids reindex would be to leave out the environment type. Dangerous because you might affect the live index when you think that you're in a test context, or when you're unaware that multiple environments point to the same search. I don't know how familiar you are with the NZ budget leaks from last year, but this can have serious ramnifications, hence I don't want to encourage any default behaviours around it.

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-search-service/commit/6a62ddaec57034b8ee33e49f07d5adbe076b50d6#diff-85ff81f090c4b7588b7de679c34cd9c4R317

**Comment by chillu** [comment]
Does this actually resolve? I can't see how this works :D 

https://github.com/silverstripe/silverstripe-search-service/commit/6a62ddaec57034b8ee33e49f07d5adbe076b50d6#diff-f1d6877f58127da9558512dcc3bb2885R44

**Comment by chillu** [comment]
Confirmed this works
