### ISSUE TITLE
IndexConfiguration->isIndexing() is misnamed

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-search-service#17]
```php
   public function isIndexing(): bool
    {
        return $this->config()->get('enable_indexing');
    }
```

When I first read the usage of this, I thought it would limit concurrency ("is indexing right now"), but that's not the case. I think we should keep some symmetry between the PHP and YAML naming, so `indexingEnabled` or `isIndexingEnabled`. We could then also rename the YAML key to `indexing_enabled`

**Comment by unclecheese** [comment]
Yup, poor choice of naming, here. Have renamed to just `enabled` and `isEnabled` (It's defined on a class called `IndexConfiguration`, so no need for `index`)
