### ISSUE TITLE
normaliseField is bound to create confusion in field naming

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-search-service#18]
`SearchServiceInterface->normaliseField()` should become `validateFieldName()`, and throw an exception instead. Unlike in silverstripe/fulltextsearch where we create an abstraction layer for *both* indexing and querying, the field name configured in your specific project context *is* part of your API - you need to reference that field name when querying the index outside of the module's control. So it's important that those field names are predictable. If you use one that the specific implementation can't work with, it should throw an error in the API call on next reindex. But we can be more helpful by also validating it in our logic.

We don’t have an “include all fields” option right? That would make it harder to follow my recommendation.

**Comment by unclecheese** [comment]
OK, but now you can't have `DataObjectDocument` declare any default fields because they're not guaranteed to validate.

I suppose that's okay, or we could make it configurable what those default fields (type / ID) are named. But then you still run the possibility that your first experience with the module is an exception.

e.g. if DataObjectDocument ships `typeName` and `ID`, and your service is lower case only, the first thing you have to do is fix that error.

Maybe safe to assume that all services will allow a lowercase string of alphanumeric characters?

**Comment by unclecheese** [comment]
Have updated this to `validateField`

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-search-service/commit/6a62ddaec57034b8ee33e49f07d5adbe076b50d6#diff-85ff81f090c4b7588b7de679c34cd9c4R238

**Comment by chillu** [comment]
> OK, but now you can't have DataObjectDocument declare any default fields because they're not guaranteed to validate.

As discussed on Zoom a while ago, I think that's fine - more explicit definition of fields by devs is a good thing here. 

> Maybe safe to assume that all services will allow a lowercase string of alphanumeric characters?

I think we should add a sentence or two around field naming in the readme close to where we put the first configuration YAML example. It's important to understand field naming in App Search for example, because you can't rename or remove fields after you've created them - you'll need to delete the engine and start over.

In terms of your AppSearch validation implementation, the rules are outlined in https://www.elastic.co/guide/en/app-search/current/schema.html#schema-errors. Assuming that API errors aren't swallowed by the implementation, that's the ultimate validation layer. We can be helpful and also validate in PHP, in which case I would recommend that you constrain it at least to those two rules:

1. "Name can only contain lowercase letters, numbers, and underscores"
2. "Name must contain a lowercase letter"

**Comment by chillu** [comment]
OK validated that's done: https://github.com/silverstripe/silverstripe-search-service/blob/master/src/Service/AppSearch/AppSearchService.php#L275
