### ISSUE TITLE
Trim down default fields

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-search-service#22]
```
$toIndex = [
            'objectSilverstripeID' => $item->ID,
            'objectTitle' => (string) $item->Title,
            'objectClassName' => get_class($item),
            'objectType' => $item->baseClass(),
            'objectClassNameHierarchy' => array_values(ClassInfo::ancestry(get_class($item))),
            'objectLastEdited' => $item->dbObject('LastEdited')->getTimestamp(),
            'objectCreated' => $item->dbObject('Created')->getTimestamp(),
            'objectLink' => str_replace(['?stage=Stage', '?stage=Live'], '', $item->AbsoluteLink())
        ];
```

This feels clunky. There's a mix of concerns in here: 

1. Fields required for module operation: `objectClassName` (currently only in Algolia)
2. Fields commonly used in search: `objectTitle`, `objectType`, `objectLink`
3. Fields less commonly used but helpful for tuning (e.g. boost by recency): `objectLastEdited`, `objectCreated`, `objectClassNameHierarchy`
4. Fields with unclear use: `objectSilverstripeID`

I think we should figure out if we need `objectClassName`, and leave everything else out. There should be examples on how best to set up default indexes with these fields. But there's really nothing special about them. Some of them make debugging easier, some of them can help authors. But given that we have a simple declarative YAML to define index fields, I don't see a reason for burying those decisions in a default implementation.

**Comment by unclecheese** [comment]
As far as I can tell, you definitely need the type / ID tuple, because otherwise you can't fetch the record from the results.

Let's reduce this to:

*  `objectSilverstripeID`
* `objectType`

And document our recommendations of:

* `Title`
* `Link`

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-search-service/commit/6a62ddaec57034b8ee33e49f07d5adbe076b50d6#diff-50b6fa13029e606508e95c84bbe77a19R128

**Comment by chillu** [comment]
> otherwise you can't fetch the record from the results.

True, you might need that if you process results through a server-side implementation, and you'd want to fetch the record to access data that isn't available in the returned search document (e.g. a thumbnail). For anyone doing a client only search implementation, that wouldn't work of course.

**Comment by unclecheese** [comment]
I think we agree there's enough of a use case here that we'll leave it as baseClass/ID tuple for now. Reopen if any objections.
