### ISSUE TITLE
ClearIndexJob will only delete documents that match the schema

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-search-service#36]
Not sure if this is really a bug but I thought I'd note it down in case it comes up and bites someone.

While testing, I indexed two documents in my engine via CURL, as per the example in the docs:

```sh
curl -X POST '<redacto>' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer <redacto>' \
  -d '[
        {
          "id": "park_rocky-mountain",
          "title": "Rocky Mountain",
          "description": "Bisected north to south by the Continental Divide, this portion of the Rockies has ecosystems varying from over 150 riparian lakes to montane and subalpine forests to treeless alpine tundra. Wildlife including mule deer, bighorn sheep, black bears, and cougars inhabit its igneous mountains and glacial valleys. Longs Peak, a classic Colorado fourteener, and the scenic Bear Lake are popular destinations, as well as the historic Trail Ridge Road, which reaches an elevation of more than 12,000 feet (3,700 m).",
          "nps_link": "https://www.nps.gov/romo/index.htm",
          "states": [
            "Colorado"
          ],
          "visitors": 4517585,
          "world_heritage_site": false,
          "location": "40.4,-105.58",
          "acres": 265795.2,
          "square_km": 1075.6,
          "date_established": "1915-01-26T06:00:00Z"
        },
        {
          "id": "park_saguaro",
          "title": "Saguaro",
          "description": "Split into the separate Rincon Mountain and Tucson Mountain districts, this park is evidence that the dry Sonoran Desert is still home to a great variety of life spanning six biotic communities. Beyond the namesake giant saguaro cacti, there are barrel cacti, chollas, and prickly pears, as well as lesser long-nosed bats, spotted owls, and javelinas.",
          "nps_link": "https://www.nps.gov/sagu/index.htm",
          "states": [
            "Arizona"
          ],
          "visitors": 820426,
          "world_heritage_site": false,
          "location": "32.25,-110.5",
          "acres": 91715.72,
          "square_km": 371.2,
          "date_established": "1994-10-14T05:00:00Z"
        }
      ]'
```

Which worked fine and dandy. However, when I ran the `ClearIndexJob`, it found no documents with the `->listDocuments()` call, so didn't remove them, but found 2 with `->getDocumentTotal()`, causing the Job to crash.

Given a case where a developer changes a schema and wants to start fresh, we probably need something like a "force" flag on the Job that just brazenly deletes everything from the index.

**Comment by madmatt** [comment]
Hey @unclecheese, we've noticed this on another project as well and believe we're hitting the same or similar problem (I think in our case the `DataObject` no longer exists or can't be loaded because the source class doesn't exist, so it doesn't remove the document. I'm checking in the index to see what's actually listed for these documents, but I think a task like `ClearIndexJob` shouldn't rely on the full dependency tree existing (of `Document` back to `DataObject`). I wonder if it's worth having a `force=1` mode that instead calls `listDocuments` directly on the API client, though that breaks the abstraction layer a bit...

**Comment by scott1702** [comment]
> I think in our case the DataObject no longer exists

This also causes issues quite a bit during local development when changing databases (e.g. between a UAT database and local testing database), as the ClearIndexJob tries to match the elastic results with a Database record before deleting. I would be a fan of the `force=1` option that @madmatt suggested simply being the default for the job, I can't think of a scenario where someone would run the ClearIndexJob and want records not found in the Database to be kept in Elastic.

**Comment by madmatt** [comment]
I tend to agree - any thoughts @unclecheese or shall I go ahead and implement that?

I think this will require changing how `listDocuments` works...
