### ISSUE TITLE
Reindex Job finding Draft content when building list

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-search-service#42]
Had an experience where a page in draft was fetched, but then was unable to be found when looking for the content, as we explicitly look for `Live` mode in the `PageCrawler`.

We should either explicitly force Live mode when building the initial datalist, or offer a config option to include draft content.

**Comment by chillu** [comment]
We have been burned badly by allowing (Solr) search to index draft content, and then relying on devs to not mess up when using the indexed content. So this is a strong veto against including draft content. We should force live mode. 

Aside: If there's an ability to specifically reindex a URL or object, it would be nice if we made it obvious when no live version exists of that item.

**Comment by andrewandante** [comment]
I agree that my preference is to straight up ignore draft content - the PR I made returns `false` on `shoudlIndex()` if it's a `Versioned` object that's not the Live Version - I think that should cover it.
