### ISSUE TITLE
Indexed content respects Versioned constraints

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-search-service#5]
As a Silverstripe CMS developer, I want my versioned content to respect the publication constraints of the CMS so that I don't expose unpublished or archived content to the public search.

## Acceptance criteria

- [x] Pages are indexed by default
- [x] Draft dataobjects are not indexed
- [x] Unpublished dataobjects are removed from indexes

**Comment by chillu** [comment]
My take is that I don't see indexing draft content as part of the scope for this module at all. But if there's an easy way to allow for that customisation, it's worth highlighting here. Like, we shouldn't actively prevent devs from doing this, but we also don't need to make it easy (through built-in APIs or documented examples).

**Comment by chillu** [comment]
OK removing objects from draft is currently broken in master, but otherwise I've confirmed this works as expected.
