### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-search-service#56]
Is it time to release a stable 1.0.0 version?

We'd be committing to semver from that point on, but I think it feels about the right time to do this anyway - significant feature development has slowed down and things seem pretty stable. One major feature that might necessitate a major version bump is probably #29, but that's only in RFC stage so is likely quite a while away from actually having something ready.

**Comment by unclecheese** [comment]
We have a release! https://github.com/silverstripe/silverstripe-search-service/releases/tag/1.0.0
