### ISSUE TITLE
Parent Page must not be in Modified state to publish child page

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-search-service#61]
Having an issue where a page is returning `false` on `shouldIndex()` when its parent has changes on Draft that haven't been published yet.

To replicate:

1. Create and Publish a Page.
2. Create and Publish a Page as a child of that page.
3. Ensure the Child page has "inherit permissions from parent".
3. Make a change to the Parent page, Save, but do not publish.
4. Make a change to the Child page, Save and Publish.
5. Observe updates to child page are not Indexed.

Tracing this through it's because the `canView()` returns `false` on the first `$isPublic` check in `shouldIndex()`. It's returning `false` against `$page->Parent()` because the object it returns is the unpublished version, not the Live version, and an anonymous user is unable to view it. It seems to be picking that up because the reading mode is stage.Stage - not sure why that would be.

Tested running the job via CLI and through the CMS.

**Comment by jareddreyerss** [comment]
Note: the reindex task seems to suffer from this as well however it automatically indexes every page anyway so the draft versions are added to the `delete` queue and then subsequently put into the `index` queue. 🤔

**Comment by chrispenny** [comment]
@andrewandante I'm guessing this issue exists in Version 1 and Version 2, but could you please let me know which version it is you're using, so that I can prioritise a fix for that version specifically?

**Comment by andrewandante** [comment]
Hello, yes I encountered this with version 1, I have not re-tested on version 2. For myself, the fix is not super-urgent, the client has agreed to the workaround. @jareddreyerss is the one for whom this is a go-live blocker 😅

**Comment by chrispenny** [comment]
Pull request is now available, if anyone has any thoughts:
https://github.com/silverstripe/silverstripe-search-service/pull/77
