### ISSUE TITLE
The Elastic App SDK is abandoned

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-search-service#62]
Getting the following warnings when installing this module (the guzzle packages are dependencies to `elastic/app-search`:
```
Package elastic/app-search is abandoned, you should avoid using it. Use elastic/enterprise-search instead.
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
```

The suggestion is to move to https://github.com/elastic/enterprise-search-php
This sounds like it would be a smooth transition, which is mostly correct but there's a few hairballs we'll need to solve. For example we have code for updating the schema which is the following snippet:
```php
$response = $this->getClient()->updateSchema($envIndex, $definedSchema);
$this->handleError($response);
```

We would now write this as:
```php
$schemaUpdateRequest = new SchemaUpdateRequest();
$putSchema = new PutSchema($envIndex, $schemaUpdateRequest);
$response = $this->getClient()->appSearch()->putSchema($putSchema);
$this->handleError($response->asArray());
```

 You may be looking at the above and thinking to yourself, where did `$definedSchema` go? Well `SchemaUpdateRequest` doesn't have the ability to be passed any data therefore we can't actually update the schema currently, so we could look at doing something along the lines of (haven't actually tried this yet):
```php
foreach ($definedSchema as $k => $v) {
    $schemaUpdateRequest->{$k} = $v;
}
```

This feels kind of flakey, and you can also couple it with `PutSchema` and `SchemaUpdateRequest` being marked as internal classes

Perhaps we wait for the enterprise client to stabilise a bit? 🤷🏽

**Comment by ChloeSartorelli** [comment]
@chrispenny #76 has been merged and released - does that close this issue?

**Comment by chrispenny** [comment]
Indeed it does! Closing now.
