### ISSUE TITLE
After publishing a page, the queued job does not send the document for indexing

### ISSUE THREAD

**Issue by ssmarco** [silverstripe/silverstripe-search-service#75]
This issue probably started since `v1.1.0`.
When a single page is published and yes the queued job is created to send the document.
However even if the queued job is completed successfully, upon further investigation the document is not posted to Elastic endpoint. It turned out that the `$batch_size` is null as a 3rd parameter to `array_splice` which does not change the original array and returns an empty array.

https://github.com/silverstripe/silverstripe-search-service/blob/ee62b4200d6c6b37b3e87b9da8bdb70661fb5de4/src/Service/BatchProcessor.php#L36

https://github.com/silverstripe/silverstripe-search-service/blob/ee62b4200d6c6b37b3e87b9da8bdb70661fb5de4/src/Jobs/IndexJob.php#L91

I have come up a solution using the same strategy with `ReindexJob` class to apply a default batch size from configuration if the value is empty. See PR here https://github.com/silverstripe/silverstripe-search-service/pull/74

**Comment by chrispenny** [comment]
Completed in https://github.com/silverstripe/silverstripe-search-service/pull/74
