### ISSUE TITLE
Allow full page indexing

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-search-service#9]
As a Silverstripe CMS developer, I want to be able to index content types as full page renders if they have their own URL on the website so that I can get an inclusive base of content to search.

## Acceptance criteria

- [x] Full page indexing for dataobjects that have links
- [x] Can customise the field to which full page content saves
- [x] There is an API for setting what the boundaries of "Content" are versus chrome (e.g. the `<main />` tag
- [x] HTML tags can be stripped from indexed content

**Comment by chillu** [comment]
Confirmed this works. although it's a bit counter intuitive to crawl on `<main>` by default - e.g. the "simple" theme doesn't use that HTML5 tag, which got me a bit confused. Just a matter of docs really.

And I've created a new issue to refactor the crawler into a resolver pattern instead https://github.com/silverstripe/silverstripe-search-service/issues/26
